<div id="footer">
    <footer>
        <nav>
            <ul>
                <li><a href="https://github.com/106131320/106131320.github.io" target="_blank">The Charity's Github
                        Page!</a></li>
                <li><a href="https://student-team-zoiq7lxh.atlassian.net/jira/software/projects/SCRUM/boards/1?jql=assignee+IN+%28712020%3Abe9216f0-d140-42bb-b60f-a7aef8324e48%2C+empty%29&atlOrigin=eyJpIjoiODg0NmZjNGFiNmYyNGUyMzhlNzUxNzFkODQyN2M4N2EiLCJwIjoiaiJ9"
                        target="_blank">The Charity's Jira portfolio </a></li>
                <li><a href="mailto:theonlyrealcharity@gmail.com" target="_blank">theonlyrealcharity@gmail.com</a></li>
            </ul>
        </nav>
        <p>© 2025 The Charity</p>
    </footer>
</div>
</body>

</html>